const vendors = [
  {
    vendor_name: "Amazon Business",
    unit_price: 18,
    shipping_cost: 5,
    lead_time_days: 2,
    ai_score: 92,
    product_url: `https://www.amazon.com/s?k=${searchTerm}`,
  },
  {
    vendor_name: "Uline",
    unit_price: 21,
    shipping_cost: 8,
    lead_time_days: 3,
    ai_score: 88,
    product_url: `https://www.uline.com/Search?keywords=${searchTerm}`,
  },
  {
    vendor_name: "Grainger",
    unit_price: 20,
    shipping_cost: 6,
    lead_time_days: 2,
    ai_score: 90,
    product_url: `https://www.grainger.com/search?searchQuery=${searchTerm}`,
  },
  {
    vendor_name: "Alibaba",
    unit_price: 12,
    shipping_cost: 15,
    lead_time_days: 10,
    ai_score: 75,
    product_url: `https://www.alibaba.com/trade/search?SearchText=${searchTerm}`,
  },
  {
    vendor_name: "Global Industrial",
    unit_price: 19,
    shipping_cost: 7,
    lead_time_days: 4,
    ai_score: 86,
    product_url: `https://www.globalindustrial.com/searchResult?text=${searchTerm}`,
  },
  {
    vendor_name: "Staples Business",
    unit_price: 22,
    shipping_cost: 4,
    lead_time_days: 2,
    ai_score: 84,
    product_url: `https://www.staples.com/search?query=${searchTerm}`,
  },
  {
    vendor_name: "Office Depot",
    unit_price: 23,
    shipping_cost: 5,
    lead_time_days: 3,
    ai_score: 82,
    product_url: `https://www.officedepot.com/a/search/?q=${searchTerm}`,
  },
  {
    vendor_name: "Fastenal",
    unit_price: 24,
    shipping_cost: 6,
    lead_time_days: 2,
    ai_score: 87,
    product_url: `https://www.fastenal.com/search?query=${searchTerm}`,
  },
  {
    vendor_name: "MSC Industrial",
    unit_price: 25,
    shipping_cost: 7,
    lead_time_days: 3,
    ai_score: 85,
    product_url: `https://www.mscdirect.com/browse/tn?searchterm=${searchTerm}`,
  },
  {
    vendor_name: "Walmart Business",
    unit_price: 17,
    shipping_cost: 6,
    lead_time_days: 3,
    ai_score: 80,
    product_url: `https://www.walmart.com/search?q=${searchTerm}`,
  },
];
